### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by jimrthy** [gfxfundamentals/threejsfundamentals#46]
I just read through the article on OffscreenCanvas and web workers.

Firefox has had partial, experimental support for several versions now. I went ahead and enabled it to see what happened.

The verification check to see whether canvas has a `transferControlToOffscreen` property started passing. But the actual code fails, because the workers don't have access to requestAnimationFrame.

I don't think there's anything to change here. You aren't producing a commercial game that needs to work everywhere. I just thought the quirky information might be worth sharing, and I didn't see a better way to supply feedback.

On a different note, the page works fine in Chromium.

Thank you so much for an extremely helpful site. I'm learning a lot.

**Comment by greggman** [comment]
I'm not sure what your suggestion is.

It says right at the top of the article

> OffscreenCanvas is a relatively new browser feature currently only available in Chrome ...

There's a reason the feature is not on in Firefox by default. That's because it doesn't actually work correctly yet. Until then there's no point in trying to make it work for Firerfox. When Firefox finishes their implemetion it will should start working. No need to change anything.

Here's the related issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1469282

**Comment by jimrthy** [comment]
There isn't anything to change. This was really just feedback.
