### ISSUE TITLE
Request: Points and other types of Objects

### ISSUE THREAD

**Issue by nchase** [gfxfundamentals/threejsfundamentals#48]
I noticed classes for Points, Bones, and other kinds of classes for 'Objects' in ThreeJS. As a novice, it's not clear to me how to use them and I haven't seen them mentioned in the content here. Some mention of them in these articles and how they relate to the other topics discussed here would be extremely helpful.

This is a pretty awesome project by the way, thank you for the hard work 🌞

**Comment by greggman** [comment]
Here's the list from the three.js docs

* Bone
* Group
* InstancedMesh
* Line
* LineLoop
* LineSegments
* LOD
* Mesh
* Points
* Skeleton
* SkinnedMesh
* Sprite

of those `Points` is mentioned in [this article](https://threejsfundamentals.org/threejs/lessons/threejs-primitives.html).

`Line`, `LineLoop` and `LineSegments` are like `Points` but they draw lines. `Line` draw one line through each vertex position. `LineLoop` is just like `Line` except also draws one more line between the last and first vertex. `LineSegments` draws one line between every 2 vertex positions.  I personally would never use `Line` or `LineLoop` only `LineSegments`

`Bone` is basically just another name for `Object3D`. You don't normally create them by hand because most things reguarding bones requires lots of data that is hard to program by hand. That data is usually made in some 3D animation program like Blender or Maya or 3DSMax and then exported to some format that supports "skinned" models like glTF.

I don't know why three.js chose to make class called `Bone`. Most 3D engines don't do this. They'd just have `Object3D` and a collection of bones would just be some array of `Object3D`s. In fact three.js has that array, it's called a `Skeleton` but I have no idea why they decided to call the things they point to `Bone`. It's not a normal pattern.

`SkinnedMesh` is actually used to display skinned geometry using `Skeleton`

The only sample that uses `Bone`s but only indirectly is [the article on starting to make a game](https://threejsfundamentals.org/threejs/lessons/threejs-game.html) and it never actually mentions `Bone` they just happen to be used inside the models that are loaded.

If you're curious what's really happening with skinnedmesh/skeletons/bones you can read [this article](https://webglfundamentals.org/webgl/lessons/webgl-skinning.html) but it's very low-level and not directly about three.js. Like I said above, mostly you only use these somewhat indirectly by loading a skinned model from a glTF file.

`Group`, like `Bone` has no point. Most 3D engines would just use `Object3D`. The three.js docs say as much. They claim it's just a way to help you know is a group and what is not a group. I'd do that using names. Again most 3D engines don't have this concept.

`Mesh` is used all over. 

`Sprite` is used in [the article on billboards](https://threejsfundamentals.org/threejs/lessons/threejs-billboards.html)

So that leaves only `LOD` and `InstancedMesh`. I'll have to see if I have time to write articles on those but I feel like for most people they aren't that important so they've been a low-priority.

**Comment by nchase** [comment]
@greggman you're amazing. thank you!!
